<?php

include_once('osso_provider.features.inc');

/**
 * Implementation of hook_block().
 */
function osso_provider_block($op = 'list', $delta = '') {
  switch ($op) {
    case 'list':
      return array(
        'login_message' => array('info' => t('Login page message')),
        'welcome_message' => array('info' => t('Welcome message')),
      );
    case 'view':
      if (function_exists('osso_provider_block_'. $delta)) {
        return call_user_func('osso_provider_block_'. $delta);
      }
      break;
  }
}

/**
 * Implementation of hook_user().
 */
function osso_provider_user($op, &$edit, &$account) {
  switch ($op) {
    case 'view':
      // Remove all default content from the user page.
      $account->content = array();
      break;
  }
}

/**
 * Implementation hook_menu_alter().
 */
function osso_provider_menu_alter(&$items) {
  $items['user']['title callback'] = 'osso_provider_user_menu_title';
  $items['user/register']['title callback'] = 'osso_provider_register_menu_title';
}

/**
 * Custom title callback.
 */
function osso_provider_user_menu_title() {
  global $user;
  if ($user->uid) {
    return t('Hello @user', array('@user' => $user->name));
  }
  return t('Log in / Sign up');
}

/**
 * Custom title callback.
 */
function osso_provider_register_menu_title() {
  return t('Sign up');
}

/**
 * Generate hub bar.
 */
function osso_hub_bar() {
  global $user;

  // Generate links to relying parties.
  $items = array();
  $items[] = array(
    'data' => l(check_plain(variable_get('site_name', 'Drupal')), ''),
    'class' => 'provider',
  );
  foreach (openid_provider_sso_relying_parties() as $rp) {
    $items[] = array(
      'data' => l(check_plain($rp['name']), $rp['realm']),
      'class' => 'relying',
    );
  }
  $output = theme('item_list', $items, NULL, 'ul', array('class' => 'links hub-links'));

  // Generate user links.
  $items = array();
  if ($user->uid) {
    $items[] = array(
      'data' => l(t('Hello, @user', array('@user' => $user->name)), 'user/'. $user->uid),
      'class' => 'username',
    );
    $items[] = array(
      'data' => l(t('Log out'), 'logout'),
      'class' => 'logout',
    );
  }
  else {
    $items[] = array(
      'data' => l(t('Log in / Sign up'), 'user/login'),
      'class' => 'login',
    );
  }
  $output .= theme('item_list', $items, NULL, 'ul', array('class' => 'links user-links'));

  return $output;
}

/**
 * Login page message.
 */
function osso_provider_block_login_message() {
  $output = '<div class="sso-message">';
  if (isset($_SESSION['openid_provider']['request']['openid.realm']) && $relying_party = openid_provider_sso_relying_party($_SESSION['openid_provider']['request']['openid.realm'])) {
    drupal_set_title(t('Login to @relying_party', array('@relying_party' => $relying_party['name'])));
    $output .= '<p>'. t('<strong>@relying_party</strong> is part of <strong>@site_name</strong>. ', array('@site_name' => variable_get('site_name', 'Drupal'), '@relying_party' => $relying_party['name'])) .'</p>';
  }
  $output .= '<p>'. t('An account on @site_name gives you easy access to a series of sites with a single username and password.', array('@site_name' => variable_get('site_name', 'Drupal'))) .'</p>';
  $output .= '</div>';
  return array(
    'subject' => t('User login'),
    'content' => $output,
  );
}

/**
 * Welcome page message.
 */
function osso_provider_block_welcome_message() {
  $relying_parties = array();

  foreach (variable_get('openid_provider_sso_rps', array()) as $rp) {
    $relying_parties[] = $rp['name'];
  }

  $examples = array_pop($relying_parties);
  if ($relying_parties = implode(', ', $relying_parties)) {
    $examples = $relying_parties .' or '. $examples;
  }

  $content = t('<p>@site_name is your key to a host of sites.</p>',  array('@site_name' => variable_get('site_name', 'Drupal')));
  $content .= t('<p>Create an account once, and gain easy access with one username and password to sites like !examples.</p>',  array('!examples' => $examples));

  return array(
    'title' => t('Welcome'),
    'content' => $content,
  );
}

/**
 * Implementation of hook_context_plugins().
 *
 * This is a ctools plugins hook.
 */
function osso_provider_context_plugins() {
  return array(
    'osso_provider_context_condition_user_page' => array(
      'handler' => array(
        'path' => drupal_get_path('module', 'osso_provider') .'/plugins',
        'file' => 'osso_provider_context_condition_user_page.inc',
        'class' => 'osso_provider_context_condition_user_page',
        'parent' => 'context_condition',
      ),
    ),
  );
}

/**
 * Implementation of hook_context_registry().
 */
function osso_provider_context_registry() {
  $registry = array();
  $registry['conditions'] = array(
    'user_page' => array(
      'title' => t('User page'),
      'description' => t('Set this context when viewing a user page.'),
      'plugin' => 'osso_provider_context_condition_user_page',
    ),
  );
  return $registry;
}

function osso_provider_context_page_condition() {
  if ($plugin = context_get_plugin('condition', 'user_page')) {
    $plugin->execute();
  }
}
