<?php

include_once('osso_provider.features.inc');

/**
 * Implementation of hook_block().
 */
function osso_provider_block($op = 'list', $delta = '') {
  switch ($op) {
    case 'list':
      return array(
        'login_message' => array('info' => t('Login page message')),
        'welcome_message' => array('info' => t('Welcome message')),
        'site_network' => array('info' => t('Site network')),
      );
    case 'view':
      module_load_include('inc', 'osso_provider', 'osso_provider.block');
      if (function_exists('osso_provider_block_'. $delta)) {
        return call_user_func('osso_provider_block_'. $delta);
      }
      break;
  }
}

/**
 * Implementation of hook_user().
 */
function osso_provider_user($op, &$edit, &$account) {
  switch ($op) {
    case 'view':
      // Remove all default content from the user page.
      $account->content = array();
      break;
  }
}

/**
 * Implementation hook_menu_alter().
 */
function osso_provider_menu_alter(&$items) {
  $items['user']['title callback'] = 'osso_provider_user_menu_title';
  $items['user/register']['title callback'] = 'osso_provider_register_menu_title';
}

/**
 * Custom title callback.
 */
function osso_provider_user_menu_title() {
  global $user;
  if ($user->uid) {
    return t('Hello @user', array('@user' => $user->name));
  }
  return t('Log in / Sign up');
}

/**
 * Custom title callback.
 */
function osso_provider_register_menu_title() {
  return t('Sign up');
}

/**
 * Implementation of hook_context_plugins().
 *
 * This is a ctools plugins hook.
 */
function osso_provider_context_plugins() {
  return array(
    'osso_provider_context_condition_user_page' => array(
      'handler' => array(
        'path' => drupal_get_path('module', 'osso_provider') .'/plugins',
        'file' => 'osso_provider_context_condition_user_page.inc',
        'class' => 'osso_provider_context_condition_user_page',
        'parent' => 'context_condition',
      ),
    ),
  );
}

/**
 * Implementation of hook_context_registry().
 */
function osso_provider_context_registry() {
  $registry = array();
  $registry['conditions'] = array(
    'user_page' => array(
      'title' => t('User page'),
      'description' => t('Set this context when viewing a user page.'),
      'plugin' => 'osso_provider_context_condition_user_page',
    ),
  );
  return $registry;
}

function osso_provider_context_page_condition() {
  if ($plugin = context_get_plugin('condition', 'user_page')) {
    $plugin->execute();
  }
}
